---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: malachite

description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 43  

modules:
  - type: akmods
    install: []
    nvidia-driver: nvidia
    
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into root
  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      copr:
        - zeno/scrcpy
        - scottames/ghostty
        - shdwchn10/AllTheTools
        - alternateved/keyd
        - lihaohong/yazi
        - bieszczaders/kernel-cachyos
    install:
      packages:
        #- https://github.com/oscar370/Matuda/releases/download/v1.0.1/Matuda-1.0.0-1.x86_64.rpm
        #- btop
        #- npm
        #- npx
        #- nvtop
        # - openmw
        # - openmw-tools
        - zed-preview
        - libxcrypt-compat
        - gnome-tweaks
        - fish        
        - https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64
        - podman-remote
        - podman-docker        
        - distrobox        
        - policycoreutils-python-utils
        - mpv
        - nnn
        - dmtcp
        - libinput-utils
        - openssl-devel
        - thinkfan
        - lm_sensors
        - hashcat
        - stress
        - cargo
        - poppler
        - fd-find
        - yazi
        - cmake
        - meson
        - gcc-c++
        - gcc
        - igt-gpu-tools
        - vkmark
        - vulkan-tools
        - uv
        - ghostty
        - sdrpp
        - zoxide
        - kernel-tools
        - tailscale
        - bat
        - eza
        - zsh
        - msr-tools
        - topgrade
        - powertop
        - adw-gtk3-theme
        # - rapid-photo-downloader
        - rtl-sdr
        - gqrx
        - sdrangel
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: script
    snippets:
      - "rm /usr/share/backgrounds/gnome/*"
  - type: signing
  #   nofile-limits: true # increase nofile limits
  #   brew-analytics: false # disable telemetry
