---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: malachite
# description will be included in the image's metadata
description: This is my personal OS image.
# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/silverblue-main
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest  # latest is also supported if you want new updates ASAP
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: akmods
  #   base: main
  #   install:
  #     - nvidia
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* into root
  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr:
        #- amneziavpn/amneziawg
        - zeno/scrcpy
        - pgdev/ghostty
        - shdwchn10/AllTheTools
        - alternateved/keyd
        - lihaohong/yazi
        - bieszczaders/kernel-cachyos
    optfix:
      - windscribe
    install:
      packages:
        - nnn
        - dmtcp
        - libinput-utils
        - https://github.com/Windscribe/Desktop-App/releases/download/v2.16.11/windscribe_2.16.11_amd64_fedora.rpm
        #- https://github.com/Windscribe/Desktop-App/releases/download/v2.16.4/windscribe_2.16.4_guinea_pig_amd64_fedora.rpm
        #- amneziawg-dkms 
        #- amneziawg-tools
        - openssl-devel
        - thinkfan
        - lm_sensors
        #- libssl-dev
        #- kernel-cachyos
        - hashcat
        - stress
        - cargo
        - poppler
        - fd-find
        - yazi
        # ********************************************
        - cmake
        - meson
        - gcc-c++
        - gcc
        - igt-gpu-tools
        - vkmark
        - vulkan-tools
        # - cuda
        # - nvenc
        # - nvidia-driver-cuda
        # - nvidia-driver-NvFBCOpenGL
        - uv
        # - scrcpy
        # - astroterm
        - ghostty
        - sdrpp
        - zoxide
        # - keyd
        - kernel-tools
        - tailscale
        - bat
        - eza
        # - fish
        - zsh
        - msr-tools
        - topgrade
        - powertop
        # - python3.11
        # - python3.12
        - adw-gtk3-theme
        - rapid-photo-downloader
        - rtl-sdr
        - gqrx
        - sdrangel
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - from-file: hyprland.yml
  - type: script
    snippets:
      - "rm /usr/share/backgrounds/gnome/pride*"
      - "rm /usr/share/backgrounds/gnome/progress*"
  # - type: default-flatpaks
  #   notify: true  # Send notification after install
  #   system:
  #     # If no repo information is specified, Flathub will be used by default
  #     install:
  #       - org.mozilla.firefox
  #       - org.gnome.Loupe
  #     remove:
  #       - org.gnome.eog
    user: {}  # Also add Flathub user repo, but no user packages
  - type: signing  # this sets up the proper policy & signing

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
