---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: malachite
# description will be included in the image's metadata
description: This is my personal OS image.
# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/silverblue-main
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest  # latest is also supported if you want new updates ASAP
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: akmods
  #   base: main
  #   install:
  #     - nvidia
  # - type: files
  #   files:
  #     - source: system
  #       destination: / # copies files/system/* into root
  - type: dnf
    repos:
      copr:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/repo/fedora-%OS_VERSION%/zeno-scrcpy-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/shdwchn10/AllTheTools/repo/fedora-%OS_VERSION%/shdwchn10-AllTheTools-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/alternateved/keyd/repo/fedora-%OS_VERSION%/alternateved-keyd-fedora-%OS_VERSION%.repo
    install:
      packages:
        #- cuda
        #- nvenc
        #- nvidia-driver-cuda
        #- nvidia-driver-NvFBCOpenGL
        - uv
        #- scrcpy
        #- astroterm
        - ghostty
        - sdrpp
        - zoxide
        #- keyd
        - kernel-tools
        - tailscale
        - bat
        - eza
        #- fish
        - zsh
        - msr-tools
        - topgrade
        - powertop
        #- python3.11
        #- python3.12
        - adw-gtk3-theme
        - rapid-photo-downloader
        - rtl-sdr
        - gqrx
        - sdrangel
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: default-flatpaks
    notify: true # Send notification after install
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages
  - type: signing # this sets up the proper policy & signing
