---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: malachite
# description will be included in the image's metadata
description: This is my personal OS image.
# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/silverblue-main
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: latest  # latest is also supported if you want new updates ASAP
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: akmods
  #   base: main
  #   install:
  #     - nvidia
  # - type: files
  #   files:
  #     - source: system
  #       destination: / # copies files/system/* into root
  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr:
        - zeno/scrcpy
        - pgdev/ghostty
        - shdwchn10/AllTheTools
        - alternateved/keyd
        - solopasha/hyprland
    install:
      packages:
        # - cuda
        # - nvenc
        # - nvidia-driver-cuda
        # - nvidia-driver-NvFBCOpenGL
        - uv
        # - scrcpy
        # - astroterm
        - ghostty
        - sdrpp
        - zoxide
        # - keyd
        - kernel-tools
        - tailscale
        - bat
        - eza
        # - fish
        - zsh
        - msr-tools
        - topgrade
        - powertop
        # - python3.11
        # - python3.12
        - adw-gtk3-theme
        - rapid-photo-downloader
        - rtl-sdr
        - gqrx
        - sdrangel
        # ************** HYPRLAND RELATED THINGS ******************
        # Core compositors
        - hyprland
        - hyprland-git
        - hyprland-legacyrenderer
        # Plugins & extensions
        - hyprland-plugins
        - hyprland-plugins-git
        - hyprland-contrib
        - hyprland-autoname-workspaces
        - hyprland-polkitagent
        # Session helpers & portals
        - xdg-desktop-portal-hyprland
        - gnome-keyring
        # Wallpapers & lockscreen
        - hyprpaper
        - swww
        - waypaper
        - hyprlock
        - mpvpaper
        - hyprsunset
        # Panels, widgets & bars
        - hyprpanel
        - waybar-git
        - eww-git
        - aylurs-gtk-shell
        - aylurs-gtk-shell2
        # Utilities
        - hypridle
        - hyprshot
        - hyprpicker
        - hyprsysteminfo
        - hyprdim
        - satty
        - cliphist
        - nwg-clipman
        - swaylock-effects
        - pyprland
        - uwsm
        # Essentials
        - dunst
        - alacritty
        - pavucontrol
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: default-flatpaks
    notify: true  # Send notification after install
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {}  # Also add Flathub user repo, but no user packages
  - type: signing  # this sets up the proper policy & signing
